import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=metal','--enable-gpu','--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs=[]; p.on('console',m=>m.type()==='error'&&errs.push(m.text())); p.on('pageerror',e=>errs.push('pageerror: '+e.message));
await p.goto('http://127.0.0.1:4173/', { waitUntil: 'load' });
await p.waitForFunction(() => Boolean(window.__LV), null, { timeout: 45000 });
await p.evaluate(() => window.__LV.ready());
await p.evaluate(() => { window.__LV.startRun(); window.__LV.setAutopilot(true,{skill:1}); });
await p.waitForTimeout(5000);
// Feed the flight model a poisoned command, the most plausible route to a non-finite state.
await p.evaluate(() => window.__LV.setInput({ throttle: NaN, pitch: NaN, yaw: Infinity, roll: -Infinity }));
await p.waitForTimeout(1500);
const mid = await p.evaluate(() => ({ pose: window.__LV.pose(), t: window.__LV.telemetry().speed, errs: window.__LV.errors().length }));
await p.evaluate(() => window.__LV.setInput(null));
await p.waitForTimeout(2500);
const after = await p.evaluate(() => ({ pose: window.__LV.pose(), speed: window.__LV.telemetry().speed, phase: window.__LV.phase(), errs: window.__LV.errors() }));
const finite = a => a.every(Number.isFinite);
console.log('during poison  → position finite:', finite(mid.pose.position), 'velocity finite:', finite(mid.pose.velocity), 'page errors:', errs.length);
console.log('after recovery → position finite:', finite(after.pose.position), 'speed:', Math.round(after.speed), 'phase:', after.phase);
console.log('errors:', errs.slice(0,4), 'game errors:', after.errs.slice(0,3));
await b.close();
