import { spawn } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { isAbsolute, resolve } from 'node:path';
import { REPO_ROOT } from './runtime.mjs';
import { suiteFailures } from './manifest.mjs';

const started = Date.now();
const { outputRoot, forwardedArgs } = extractOutput(process.argv.slice(2));
const suites = [
  // Performance FIRST, and with a settle window between every suite.
  //
  // Run after another browser suite, the perf arms were measuring the previous Chromium's
  // teardown rather than the game: inside all.mjs they produced a 66 ms worst frame and 5-24 long
  // frames, while two standalone runs on the same commit and comparable host load gave 16.67 ms
  // mean, 18.6 ms worst and ZERO long frames. That is the uncontrolled-load failure this project
  // has spent four review rounds criticising in others, generated by our own harness.
  { name: 'perf-probe', script: 'perf-probe.mjs' },
  { name: 'perf-probe-hidpi', script: 'perf-probe.mjs', args: ['--device-scale-factor', '2'] },
  // The normal and HiDPI variants keep the paired plume visible from its authored side camera.
  // The cockpit performance probe cannot cover this effect because first-person mode hides the
  // exterior ship by design.
  { name: 'boost-vfx-probe', script: 'boost-vfx-probe.mjs' },
  { name: 'boost-vfx-probe-hidpi', script: 'boost-vfx-probe.mjs', args: ['--device-scale-factor', '2'] },
  { name: 'i18n-contract', script: 'i18n-contract.mjs' },
  { name: 'campaign-contract', script: 'campaign-contract.mjs' },
  { name: 'localization', script: 'localization.mjs' },
  { name: 'localization-hidpi', script: 'localization.mjs', args: ['--device-scale-factor', '2'] },
  { name: 'playtest', script: 'playtest.mjs' },
  { name: 'campaign', script: 'campaign.mjs' },
  { name: 'screenshot-matrix', script: 'screenshot-matrix.mjs' },
  // Nobody has heard this build, so the offline audio measurement IS the audio quality gate —
  // and a gate that is not run does not gate. --require-clean because everything this suite
  // produces is quoted as evidence.
  { name: 'audio-probe', script: 'audio-probe.mjs', args: ['--require-clean', '--artifact-locked'] },
  // A real AudioContext in a real browser. The offline probe is blind to suspension and to the
  // mix state machine BY CONSTRUCTION, and both round-4 audio blockers lived in that gap.
  { name: 'audio-live', script: 'audio-live.mjs', args: ['--require-clean', '--artifact-locked'] },
];

/** Milliseconds to let the machine settle after a suite's browser has exited. */
const SETTLE_MS = 3_000;
const results = [];

await mkdir(outputRoot, { recursive: true });
for (const suite of suites) {
  const suiteOutput = resolve(outputRoot, suite.name);
  const script = resolve(REPO_ROOT, 'scripts/playtest', suite.script);
  const execution = await runChild(script, [...forwardedArgs, ...(suite.args ?? []), '--out', suiteOutput]);
  // Let the child's browser finish exiting before the next suite starts measuring anything.
  await new Promise((resolve) => { setTimeout(resolve, SETTLE_MS); });
  let report = null;
  let reportError = null;
  try {
    report = JSON.parse(await readFile(resolve(suiteOutput, 'report.json'), 'utf8'));
  } catch (error) {
    reportError = error instanceof Error ? error.message : String(error);
  }
  results.push({
    suite: suite.name,
    exitCode: execution.exitCode,
    signal: execution.signal,
    stdout: execution.stdout,
    stderr: execution.stderr,
    reportPath: relativeOutput(resolve(suiteOutput, 'report.json')),
    status: report?.status ?? 'FAIL',
    summary: report?.summary ?? null,
    checkIds: Array.isArray(report?.checks) ? report.checks.map((c) => c?.id).filter(Boolean) : [],
    reportError,
  });
}

const finished = Date.now();

/**
 * A suite passes only if it BOTH reported PASS and actually completed.
 *
 * This used to be `result.status === 'PASS'` alone, which made the aggregate blind to a child that
 * wrote a nominal PASS report and then aborted. That is not hypothetical: `--require-clean` writes
 * its report and exits 2, so the clean-tree enforcement added this session could never have failed
 * the gate it was added to. Reproduced directly — dirty tree, `audio-probe --require-clean` exits 2
 * with `status: PASS` in its own report, and the aggregate went green.
 *
 * Found by an independent agent from a different family, on a first pass, after five rounds of
 * eight-discipline review had looked at the game and never at the aggregator.
 */
for (const result of results) result.failures = suiteFailures(result);
const status = results.every((result) => result.failures.length === 0) ? 'PASS' : 'FAIL';
const combined = {
  schemaVersion: 1,
  suite: 'all',
  status,
  startedAt: new Date(started).toISOString(),
  finishedAt: new Date(finished).toISOString(),
  durationMs: finished - started,
  outputRoot: relativeOutput(outputRoot),
  suites: results,
};
const combinedPath = resolve(outputRoot, 'report.json');
await writeFile(combinedPath, `${JSON.stringify(combined, null, 2)}\n`, 'utf8');
for (const result of results) {
  if (result.failures.length > 0) {
    process.stdout.write(`  FAIL ${result.suite}: ${result.failures.join('; ')}\n`);
  }
}
process.stdout.write(`${status}: ${combinedPath}\n`);
process.exitCode = status === 'PASS' ? 0 : 1;

function extractOutput(argv) {
  const outputArgs = [];
  let output = resolve(REPO_ROOT, 'playtest-out');
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--out') {
      const value = argv[index + 1];
      if (value && !value.startsWith('--')) {
        output = absoluteFromRepo(value);
        index += 1;
        continue;
      }
    }
    if (arg.startsWith('--out=')) {
      output = absoluteFromRepo(arg.slice('--out='.length));
      continue;
    }
    outputArgs.push(arg);
  }
  return { outputRoot: output, forwardedArgs: outputArgs };
}

function runChild(script, args) {
  return new Promise((resolveExecution) => {
    const child = spawn(process.execPath, [script, ...args], {
      cwd: REPO_ROOT,
      env: { ...process.env },
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
      process.stdout.write(chunk);
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
      process.stderr.write(chunk);
    });
    child.once('error', (error) => {
      resolveExecution({ exitCode: null, signal: null, stdout, stderr: `${stderr}${error.message}\n` });
    });
    child.once('exit', (exitCode, signal) => {
      resolveExecution({ exitCode, signal, stdout, stderr });
    });
  });
}

function absoluteFromRepo(path) {
  return isAbsolute(path) ? path : resolve(REPO_ROOT, path);
}

function relativeOutput(path) {
  return path.startsWith(`${REPO_ROOT}/`) ? path.slice(REPO_ROOT.length + 1) : path;
}
